apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-service
  labels:
    app: register-service-deployment
spec:
  selector:
    matchLabels:
      app: register-service-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: register-service-pod
    spec:
      containers:
        - name: register-service
          image: sebsatian/register-service
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REGISTER
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_REGISTER
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REGISTER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REGISTER
            - name: CONFIG_SERVER_HOST
              value: "config-server"
            - name: EUREKA_HOST
              value: "eureka-server"
            - name: EUREKA_PORT
              value: "8761"
            - name: INSTANCE_HOSTNAME
              value: register-service
---
apiVersion: v1
kind: Service
metadata:
  name: register-service
  labels:
    app: register-service-deployment
spec:
  clusterIP: None
  selector:
    app: register-service-pod
  ports:
    - protocol: TCP
      port: 8080 # Puerto dummy para no afectar puertos dinámicos
      targetPort: 8080