server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/client/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/requests/**,/firsthomereq/**,/secondhomereq/**,/businessreq/**,/remodelingreq/**
        - id: simulation-service
          uri: lb://simulation-service
          predicates:
            - Path=/simulation/**,/loan-types/**
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/evaluation/**
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/tracking/**
        - id: totalcosts-service
          uri: lb://totalcosts-service
          predicates:
            - Path=/total-costs/**
