apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-request-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db-request-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-request-pvc
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-request
  labels:
    app: db-request-deployment
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-request-pod
  template:
    metadata:
      labels:
        app: db-request-pod
        tier: database
    spec:
      containers:
        - name: db-request
          image: postgres:16
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REQUEST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REQUEST             
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-request-data
            - mountPath: /docker-entrypoint-initdb.d
              name: init-scripts
          
      volumes:
        - name: db-request-data
          persistentVolumeClaim:
            claimName: db-request-pvc
        - name: init-scripts
          configMap:
            name: prestabanco-request-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: db-request-service
  labels:
    app: db-request-service
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: db-request-pod
    tier: database
  type: LoadBalancer