apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_REGISTER: db-register-service
  DB_DBNAME_REGISTER: register_db
  DB_HOST_SIMULATION: db-simulation-service
  DB_DBNAME_SIMULATION: simulation_db
  DB_HOST_REQUEST: db-request-service
  DB_DBNAME_REQUEST: request_db
  DB_HOST_EVALUATION: db-evaluation-service
  DB_DBNAME_EVALUATION: evaluation_db
  DB_HOST_TRACKING: db-tracking-service
  DB_DBNAME_TRACKING: tracking_db
  DB_HOST_TOTALCOST: db-totalcost-service
  DB_DBNAME_TOTALCOST: totalcost_db
  DB_PORT: "5432"
---
# Creation and insertion of loan types
apiVersion: v1
kind: ConfigMap
metadata:
  name: simulation-init-scripts
data:
  init.sql: |
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 
            FROM information_schema.tables 
            WHERE table_name = 'loan_types'
        ) THEN
            CREATE TABLE loan_types (
                id SERIAL PRIMARY KEY,
                type VARCHAR(255) NOT NULL,
                maximum_term INT NOT NULL,
                max_finance DECIMAL(5, 2) NOT NULL,
                min_interest_rate DECIMAL(5, 2) NOT NULL,
                max_interest_rate DECIMAL(5, 2) NOT NULL,
                annual_interest_rate DECIMAL(5, 2) NOT NULL
            );
            INSERT INTO loan_types (type, maximum_term, max_finance, min_interest_rate, max_interest_rate, annual_interest_rate)
            VALUES
            ('Primera Vivienda', 30, 0.80, 3.5, 5.0, 5.0),
            ('Segunda Vivienda', 20, 0.70, 4.0, 6.0, 6.0),
            ('Propiedades Comerciales', 25, 0.60, 5.0, 7.0, 7.0),
            ('Remodelación', 15, 0.50, 4.5, 6.0, 6.0);
        END IF;
    END $$;
