apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_REGISTER: db-register-service
  DB_DBNAME_REGISTER: register_db
  DB_HOST_SIMULATION: db-simulation-service
  DB_DBNAME_SIMULATION: simulation_db
  DB_HOST_REQUEST: db-request-service
  DB_DBNAME_REQUEST: request_db
  DB_HOST_EVALUATION: db-evaluation-service
  DB_DBNAME_EVALUATION: evaluation_db
  DB_HOST_TRACKING: db-tracking-service
  DB_DBNAME_TRACKING: tracking_db
  DB_HOST_TOTALCOST: db-totalcost-service
  DB_DBNAME_TOTALCOST: totalcost_db
  DB_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: register-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE register_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'register_db')\gexec
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simulation-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE simulation_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'simulation_db')\gexec
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: request-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE request_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'request_db')\gexec
---    
apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE evaluation_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'evaluation_db')\gexec
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE tracking_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'tracking_db')\gexec
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: totalcost-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE totalcost_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'totalcost_db')\gexec 