server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: file:///C:/Users/seba/Desktop/PrestaBanco_TINGESOEV2
          search-paths: config-data

  application:
    name: config-service
