server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/seba/Desktop/PrestaBanco_TINGESOEV2/Backend/config-data
  application:
    name: config-server
