server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/sebsatian/PrestaBanco_TINGESOEV2/
          search-paths: config-data
  application:
    name: config-server